# Generated by Django 4.1.1 on 2022-09-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=100)),
                ("Passwd", models.CharField(max_length=50)),
                ("classification", models.CharField(max_length=50)),
            ],
        ),
    ]
