# Generated by Django 4.1.2 on 2022-10-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_rename_students_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="Email", new_name="email",
        ),
        migrations.RenameField(
            model_name="student", old_name="Passwd", new_name="passwd",
        ),
    ]
